# Generated by Django 3.0.5 on 2020-04-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20200425_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'HOMETASKS', 'verbose_name_plural': 'HOMETASKS'},
        ),
    ]
