# Generated by Django 3.0.5 on 2020-04-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_auto_20200425_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
