# Generated by Django 3.0.5 on 2020-04-30 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_delete_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Homework. Homeworks', 'verbose_name_plural': 'Homeworks. Homework'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Homework. Laba 9', 'verbose_name_plural': 'Homeworks. Laba 9'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app_blog.Category', verbose_name='Homework. Laba 9'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Максимум 250 символів', max_length=250, verbose_name='Homework'),
        ),
    ]
